name: Telegram Notification

on:
  push:
    branches:
      - main  # Or your branch name

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification
        run:  echo "Triggering restart of the application" curl -X GET "${{ secrets.RESTART_URL }}"

      